{% set version = "1.26.0" %}

package:
  name: ecmwf_grib
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
  sha256: 0ca45544c54a3a67de78a62663d4be6be8d9c95a63f1bd30fcb4c14588ac9501

build:
  number: 1
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf 4.5*
    - hdf5 1.10.1
    - gcc
  run:
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf >=4.5
    - hdf5 1.10.1
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  commands:
    - grib_info
    - ls $(grib_info -t)
    - ls $(grib_info -d)
    - test -f ${PREFIX}/lib/libgrib_api.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f77.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f90.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f77.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f90.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache 2.0
  license_file: LICENSE
  summary: 'The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.'

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
    - pelson
    - rhattersley
    - kynan
