{% set version = "1.23.1" %}

package:
  name: ecmwf_grib
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
  sha256: 7b0c40bcc8794ee11385bd6b9c5230a23e2432c88c8203dfdc7ccee054535ad4

build:
  number: 1
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - jasper
    - libpng >=1.6.22,<1.6.31
    - libnetcdf 4.4.*
    - gcc
  run:
    - jasper
    - libpng >=1.6.22,<1.6.31
    - libnetcdf 4.4.*
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  commands:
    - grib_info
    - ls $(grib_info -t)
    - ls $(grib_info -d)
    - test -f ${PREFIX}/lib/libgrib_api.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f77.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api_f90.so  # [linux]
    - test -f ${PREFIX}/lib/libgrib_api.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f77.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgrib_api_f90.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache-2.0
  summary: 'The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.'

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
    - pelson
    - rhattersley
    - kynan
