travis:
  secure:
    BINSTAR_TOKEN: jWttfiVVbQ50UEdWyCj0Qz/kovzHn7hCuf+3uahrlvMmq8DOTjsWaACR0NCMYgptruf/mf5cyZDqkijC8/XJSEkrmQJ0xGHWBQtS/L2ydBl+oC4+nKzltmHTrR4lPywKeDrN/seSn1d6VPTqzFFj2EWByGYQORbSxTrFNsyanFPMcTf7crt/sTrod4s59a24O6BNUom2OU1fMZGeh5UVXdhoUqvEOurvIaAhfgG2clQdrAW2Gr/vpFa1CWIhsZWpG5HM93A8cGB7H/RHxVDHkiAGTOMgQFzyXxNkRucljkJyrgsSktxy5VkD9HdGkALD3ZxB26i9vK36u3XNqQJDWmMpDCxE2wcAVCIjTVlPWvNoBc/6+7qMTT1OVGY0YCl+7Fc2wnVl3gqIiYof1lsoLlaZ6brW47UWFbEe8hgKsCX9xCc8ZooLbdpTwJRLZ7bbfe7p35mmoGX1mXZVmYf5NjVm0qUQrspixoslt5cKeUsC/dRRjV5rp8vveCSwiHzKaVioae+1gZoVlk1dZMHsWdR4kzcBgHCBTDZO785e1cIsXQ09A1Kqk9CJqWH0kZAyzZBTiLlkD4EPLTT1qE4JdXN6TTXvv5GTbPXO0S0YPKc646CjDS0N/8cUAm0uGAmF1/tjDki9TfJ0CLziXhFswN7hsMCWh4DpG878pdDkjYI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
